source 'https://github.com/CocoaPods/Specs.git'

target 'JDFPeekaboo' do
  pod "JDFPeekaboo", :path => "../"
end

target 'Tests' do
  pod "JDFPeekaboo", :path => "../"

  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
end
